// <auto-generated />
using System;
using Capstone.HPTY.RepositoryLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone.HPTY.RepositoryLayer.Migrations
{
    [DbContext(typeof(HPTYContext))]
    [Migration("20250226090950_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionChatSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("SessionChatSessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ChatSession", b =>
                {
                    b.Property<int>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatSessionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<int>("HotpotBrothID")
                        .HasColumnType("int")
                        .HasColumnName("HotpotBrothID");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComboId");

                    b.HasIndex("HotpotBrothID");

                    b.HasIndex("IngredientId");

                    b.ToTable("Combos", (string)null);
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ComboIngredient", b =>
                {
                    b.Property<int>("ComboIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboIngredientId"));

                    b.Property<int>("ComboID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComboIngredientId");

                    b.HasIndex("IngredientID");

                    b.HasIndex("ComboID", "IngredientID");

                    b.ToTable("ComboIngredients");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ConditionLog", b =>
                {
                    b.Property<int>("ConditionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionLogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HotPotInventoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoggedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtensilID")
                        .HasColumnType("int");

                    b.HasKey("ConditionLogId");

                    b.HasIndex("HotPotInventoryId");

                    b.HasIndex("UtensilID");

                    b.ToTable("ConditionLogs");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("LoyatyPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Customization", b =>
                {
                    b.Property<int>("CustomizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizationId"));

                    b.Property<int>("ComboID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotpotBrothID")
                        .HasColumnType("int")
                        .HasColumnName("HotpotBrothID");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomizationId");

                    b.HasIndex("ComboID")
                        .IsUnique();

                    b.HasIndex("HotpotBrothID");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserID");

                    b.ToTable("Customizations", (string)null);
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.CustomizationIngredient", b =>
                {
                    b.Property<int>("CustomizationIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizationIngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomizationIngredientId");

                    b.HasIndex("IngredientID");

                    b.HasIndex("CustomizationID", "IngredientID");

                    b.ToTable("CustomizationIngredients");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Duration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("Percent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("PointCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.HotPotInventory", b =>
                {
                    b.Property<int>("HotPotInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotPotInventoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotpotId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("SeriesNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HotPotInventoryId");

                    b.HasIndex("HotpotId");

                    b.HasIndex("SeriesNumber")
                        .IsUnique();

                    b.ToTable("HotPotInventorys");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Hotpot", b =>
                {
                    b.Property<int>("HotpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotpotId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HotpotTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("InventoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMaintainDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TurtorialVideoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HotpotId");

                    b.HasIndex("HotpotTypeID");

                    b.HasIndex("TurtorialVideoID");

                    b.ToTable("Hotpots");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.HotpotType", b =>
                {
                    b.Property<int>("HotpotTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotpotTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HotpotTypeId");

                    b.ToTable("HotpotTypes");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("IngredientTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IngredientId");

                    b.HasIndex("IngredientTypeID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.IngredientPrice", b =>
                {
                    b.Property<int>("IngredientPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientPriceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IngredientPriceId");

                    b.HasIndex("IngredientID");

                    b.ToTable("IngredientPrices");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.IngredientType", b =>
                {
                    b.Property<int>("IngredientTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IngredientTypeId");

                    b.ToTable("IngredientTypes");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("DiscountID")
                        .IsUnique()
                        .HasFilter("[DiscountID] IS NOT NULL");

                    b.HasIndex("PaymentID")
                        .IsUnique()
                        .HasFilter("[PaymentID] IS NOT NULL");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("ComboID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomizationID")
                        .HasColumnType("int");

                    b.Property<int?>("HotpotID")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtensilID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ComboID")
                        .IsUnique()
                        .HasFilter("[ComboID] IS NOT NULL");

                    b.HasIndex("CustomizationID")
                        .IsUnique()
                        .HasFilter("[CustomizationID] IS NOT NULL");

                    b.HasIndex("HotpotID")
                        .IsUnique()
                        .HasFilter("[HotpotID] IS NOT NULL");

                    b.HasIndex("IngredientID")
                        .IsUnique()
                        .HasFilter("[IngredientID] IS NOT NULL");

                    b.HasIndex("OrderID");

                    b.HasIndex("UtensilID")
                        .IsUnique()
                        .HasFilter("[UtensilID] IS NOT NULL");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 2, 26, 16, 9, 49, 639, DateTimeKind.Utc).AddTicks(4250),
                            IsDelete = false,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 2, 26, 16, 9, 49, 639, DateTimeKind.Utc).AddTicks(4258),
                            IsDelete = false,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 2, 26, 16, 9, 49, 639, DateTimeKind.Utc).AddTicks(4258),
                            IsDelete = false,
                            Name = "Staff"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 2, 26, 16, 9, 49, 639, DateTimeKind.Utc).AddTicks(4259),
                            IsDelete = false,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ShippingOrder", b =>
                {
                    b.Property<int>("ShippingOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ShippingOrderId");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("StaffID");

                    b.ToTable("ShippingOrders");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StaffId");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.TurtorialVideo", b =>
                {
                    b.Property<int>("TurtorialVideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurtorialVideoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoURL")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("TurtorialVideoId");

                    b.ToTable("TurtorialVideos");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Utensil", b =>
                {
                    b.Property<int>("UtensilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtensilId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMaintainDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtensilTypeID")
                        .HasColumnType("int");

                    b.HasKey("UtensilId");

                    b.HasIndex("UtensilTypeID");

                    b.ToTable("Utensils");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.UtensilType", b =>
                {
                    b.Property<int>("UtensilTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtensilTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UtensilTypeId");

                    b.ToTable("UtensilTypes");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.WorkShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerID");

                    b.HasIndex("StaffID");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ChatMessage", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.ChatSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionChatSessionId");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ChatSession", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Combo", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", "HotpotBroth")
                        .WithMany()
                        .HasForeignKey("HotpotBrothID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", null)
                        .WithMany("CombosAsBroth")
                        .HasForeignKey("IngredientId");

                    b.Navigation("HotpotBroth");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ComboIngredient", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Combo", "Combo")
                        .WithMany("ComboIngredients")
                        .HasForeignKey("ComboID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", "Ingredient")
                        .WithMany("ComboIngredients")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ConditionLog", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.HotPotInventory", "HotPotInventory")
                        .WithMany("ConditionLogs")
                        .HasForeignKey("HotPotInventoryId");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Utensil", "Utensil")
                        .WithMany()
                        .HasForeignKey("UtensilID");

                    b.Navigation("HotPotInventory");

                    b.Navigation("Utensil");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Customer", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Customization", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Combo", "Combo")
                        .WithOne("Customization")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Customization", "ComboID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", "HotpotBroth")
                        .WithMany()
                        .HasForeignKey("HotpotBrothID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", null)
                        .WithMany("CustomizationsAsBroth")
                        .HasForeignKey("IngredientId");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "User")
                        .WithMany("Customizations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("HotpotBroth");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.CustomizationIngredient", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Customization", "Customization")
                        .WithMany("CustomizationIngredients")
                        .HasForeignKey("CustomizationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", "Ingredient")
                        .WithMany("CustomizationIngredients")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customization");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Feedback", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Order", "Order")
                        .WithOne("Feedback")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Feedback", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.HotPotInventory", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Hotpot", "Hotpot")
                        .WithMany("InventoryUnits")
                        .HasForeignKey("HotpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotpot");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Hotpot", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.HotpotType", "HotpotType")
                        .WithMany("Hotpot")
                        .HasForeignKey("HotpotTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.TurtorialVideo", "TurtorialVideo")
                        .WithMany("Hotpot")
                        .HasForeignKey("TurtorialVideoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HotpotType");

                    b.Navigation("TurtorialVideo");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Ingredient", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.IngredientType", "IngredientType")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngredientType");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.IngredientPrice", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientPrices")
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Manager", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "User")
                        .WithOne("Manager")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Manager", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Order", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Discount", "Discount")
                        .WithOne("Order")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Order", "DiscountID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Payment", "Payment")
                        .WithOne("Order")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Order", "PaymentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.OrderDetail", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Combo", "Combo")
                        .WithOne("OrderDetail")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.OrderDetail", "ComboID");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Customization", "Customization")
                        .WithOne("OrderDetail")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.OrderDetail", "CustomizationID");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Hotpot", "Hotpot")
                        .WithOne("OrderDetail")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.OrderDetail", "HotpotID");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Ingredient", "Ingredient")
                        .WithOne("OrderDetail")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.OrderDetail", "IngredientID");

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Utensil", "Utensil")
                        .WithOne("OrderDetail")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.OrderDetail", "UtensilID");

                    b.Navigation("Combo");

                    b.Navigation("Customization");

                    b.Navigation("Hotpot");

                    b.Navigation("Ingredient");

                    b.Navigation("Order");

                    b.Navigation("Utensil");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ShippingOrder", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Order", "Order")
                        .WithOne("ShippingOrder")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.ShippingOrder", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Staff", "Staff")
                        .WithMany("ShippingOrders")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Staff", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("Capstone.HPTY.ModelLayer.Entities.Staff", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.User", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Utensil", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.UtensilType", "UtensilType")
                        .WithMany("Utensils")
                        .HasForeignKey("UtensilTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtensilType");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.WorkShift", b =>
                {
                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Manager", "Manager")
                        .WithMany("WorkShifts")
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone.HPTY.ModelLayer.Entities.Staff", "Staff")
                        .WithMany("WorkShifts")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Combo", b =>
                {
                    b.Navigation("ComboIngredients");

                    b.Navigation("Customization");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Customization", b =>
                {
                    b.Navigation("CustomizationIngredients");

                    b.Navigation("OrderDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Discount", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.HotPotInventory", b =>
                {
                    b.Navigation("ConditionLogs");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Hotpot", b =>
                {
                    b.Navigation("InventoryUnits");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.HotpotType", b =>
                {
                    b.Navigation("Hotpot");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Ingredient", b =>
                {
                    b.Navigation("ComboIngredients");

                    b.Navigation("CombosAsBroth");

                    b.Navigation("CustomizationIngredients");

                    b.Navigation("CustomizationsAsBroth");

                    b.Navigation("IngredientPrices");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.IngredientType", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Manager", b =>
                {
                    b.Navigation("WorkShifts");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Order", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("OrderDetails");

                    b.Navigation("ShippingOrder");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Payment", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Staff", b =>
                {
                    b.Navigation("ShippingOrders");

                    b.Navigation("WorkShifts");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.TurtorialVideo", b =>
                {
                    b.Navigation("Hotpot");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Customizations");

                    b.Navigation("Feedbacks");

                    b.Navigation("Manager");

                    b.Navigation("Orders");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.Utensil", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("Capstone.HPTY.ModelLayer.Entities.UtensilType", b =>
                {
                    b.Navigation("Utensils");
                });
#pragma warning restore 612, 618
        }
    }
}
